#!/usr/bin/env python3
"""
notify.py - Best-effort event hook: POST engine events to the manager.

Usage (from the Asterisk dialplan or swu_ike tunnel hooks):
  notify.py <event> [arg1] [arg2] ...

Events: call_in <from>, call_out <to>, call_active <to> <token>, sms_in <from> <body_b64>,
        sms_out <to> <body_b64>, tunnel_up, tunnel_down, registered, unregistered

Reads MANAGER_URL and MDD_ID from /run/mdd-sim-gateway/engine.env (written by render.py).
Never fails the caller (all exceptions swallowed).
"""
import os
import sys
import json
import base64
import re


_EVENT_RE = re.compile(r"^[a-z][a-z0-9_]{0,63}$")
_CALL_ID_RE = re.compile(r"^[A-Za-z0-9_.:-]{1,160}$")


def parse_args(argv):
    """Parse the tiny dialplan-facing protocol without putting untrusted SIP values in a
    shell command.

    Asterisk passes every carrier/browser supplied value through BASE64_ENCODE and repeats
    ``--arg64``.  Older tunnel hooks can keep using positional arguments.  The optional call
    id is generated by Asterisk (linkedid), never by the SIP peer.
    """
    if not argv or not _EVENT_RE.fullmatch(str(argv[0])):
        return None
    event = str(argv[0])
    args = []
    source_call_id = ""
    index = 1
    while index < len(argv):
        item = str(argv[index])
        if item == "--call-id" and index + 1 < len(argv):
            candidate = str(argv[index + 1])
            if not _CALL_ID_RE.fullmatch(candidate):
                return None
            source_call_id = candidate
            index += 2
            continue
        if item == "--arg64" and index + 1 < len(argv):
            try:
                raw = base64.b64decode(str(argv[index + 1]), validate=True)
            except Exception:
                return None
            args.append(raw.decode("utf-8", errors="replace"))
            index += 2
            continue
        # Compatibility for non-dialplan hooks whose arguments are generated locally.
        args.append(item)
        index += 1
    return event, args, source_call_id


def load_env():
    env = {}
    path = os.environ.get("MDD_ENV", "/run/mdd-sim-gateway/engine.env")
    try:
        with open(path) as f:
            for line in f:
                if "=" in line:
                    k, v = line.strip().split("=", 1)
                    env[k] = v
    except Exception:
        pass
    return env


def main():
    parsed = parse_args(sys.argv[1:])
    if not parsed:
        return
    event, args, source_call_id = parsed
    env = load_env()
    manager_url = os.environ.get("MANAGER_URL") or env.get("MANAGER_URL", "")
    inst_id = os.environ.get("MDD_ID") or env.get("MDD_ID", "1")
    run_id = str(os.environ.get("MDD_ENGINE_RUN_ID") or
                 env.get("MDD_ENGINE_RUN_ID", "")).strip()
    payload = {"instance": inst_id, "event": event, "args": args}
    if run_id:
        payload["engine_run_id"] = run_id
    if source_call_id:
        payload["source_call_id"] = f"{run_id}:{source_call_id}" if run_id else source_call_id
    # Always append to a local event log so nothing is lost if the manager is down.
    try:
        os.makedirs("/logs", exist_ok=True)
        with open("/logs/events.jsonl", "a") as f:
            # Media admission tokens are short-lived capabilities. They must never enter the
            # persistent event log; record only that the canary hook ran.
            if event == "media_check":
                logged = {"instance": inst_id, "event": event, "args": ["<redacted>"]}
            else:
                logged = dict(payload)
                logged["args"] = list(args)
                if event == "call_out" and len(logged["args"]) > 1:
                    logged["args"][1] = "<redacted>"
                if event == "call_active" and len(logged["args"]) > 1:
                    logged["args"][1] = "<redacted>"
                if event == "call_result" and len(logged["args"]) > 4:
                    logged["args"][4] = "<redacted>"
            f.write(json.dumps(logged) + "\n")
    except Exception:
        pass
    if not manager_url:
        return
    try:
        import requests
        import urllib3
        urllib3.disable_warnings()
        token = os.environ.get("MANAGER_EVENT_TOKEN") or env.get("MANAGER_EVENT_TOKEN", "")
        requests.post(f"{manager_url.rstrip('/')}/api/engine/event",
                      json=payload, headers={"X-MDD-Engine-Token": token}, timeout=3, verify=False)
    except Exception:
        pass


if __name__ == "__main__":
    main()
