package com.lovitus.mddagent;
import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.hardware.usb.*;
import android.net.Uri;
import android.os.*;
import android.provider.Settings;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import com.google.zxing.integration.android.*;
import org.json.*;
import java.util.*;
import java.util.concurrent.*;

/** Native, large-target UI. No WebView, injected JS or arbitrary APDU console. */
public final class MainActivity extends Activity {
    private AgentService service;private boolean bound;private LinearLayout page,content,callBox;private TextView status,notice;
    private int tab;private EditText server,pin,username,password,number,message;private Spinner lineChoice,routeChoice;
    private JSONObject lastData;private LinearLayout messageList;
    private String selectedLine="";private JSONArray selectionSnapshot=new JSONArray();private final ExecutorService io=Executors.newSingleThreadExecutor();private final Runnable update=this::updateState;
    private final ServiceConnection binding=new ServiceConnection(){public void onServiceConnected(ComponentName n,IBinder b){service=((AgentService.LocalBinder)b).service();service.addListener(update);render();}public void onServiceDisconnected(ComponentName n){service=null;updateState();}};
    @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);build();}
    @Override protected void onStart(){super.onStart();bound=bindService(new Intent(this,AgentService.class),binding,BIND_AUTO_CREATE);}
    @Override protected void onStop(){if(service!=null)service.removeListener(update);if(bound){unbindService(binding);bound=false;}service=null;super.onStop();}
    @Override protected void onDestroy(){io.shutdown();super.onDestroy();}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
    private void build(){page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(16),dp(12),dp(16),dp(8));page.setBackgroundColor(0xfff5f7fa);
        page.setOnApplyWindowInsetsListener((v,insets)->{if(Build.VERSION.SDK_INT>=30){android.graphics.Insets i=insets.getInsets(WindowInsets.Type.systemBars());page.setPadding(dp(16)+i.left,dp(8)+i.top,dp(16)+i.right,dp(8)+i.bottom);}return insets;});
        TextView title=text(getString(R.string.app_name),24);page.addView(title);status=text("",15);page.addView(status);notice=text("",14);page.addView(notice);
        callBox=new LinearLayout(this);callBox.setOrientation(LinearLayout.VERTICAL);page.addView(callBox);
        LinearLayout tabs=new LinearLayout(this);int[] names={R.string.home,R.string.calls,R.string.messages,R.string.readers,R.string.settings};for(int i=0;i<names.length;i++){int choice=i;Button b=new Button(this);b.setText(names[i]);b.setTextSize(11);b.setPadding(0,0,0,0);b.setOnClickListener(v->{tab=choice;render();});tabs.addView(b,new LinearLayout.LayoutParams(0,dp(52),1));}page.addView(tabs);
        ScrollView scroll=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);scroll.setFillViewport(true);scroll.addView(content);page.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(page);render();}
    private TextView text(String value,int size){TextView v=new TextView(this);v.setText(value);v.setTextSize(size);v.setTextColor(0xff172334);v.setPadding(0,dp(8),0,dp(8));return v;}
    private void label(String value){content.addView(text(value,16));}
    private Button button(LinearLayout parent,String name,Runnable action){Button b=new Button(this);b.setText(name);b.setMinHeight(dp(48));b.setOnClickListener(v->{try{action.run();}catch(Exception e){error(e.getMessage());}});parent.addView(b);return b;}
    private Button button(int name,Runnable action){return button(content,getString(name),action);}
    private EditText input(int hint,boolean secret){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(true);e.setTextSize(16);e.setPadding(dp(10),dp(10),dp(10),dp(10));e.setInputType(secret?InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD:InputType.TYPE_CLASS_TEXT);content.addView(e);return e;}
    private void error(String message){new AlertDialog.Builder(this).setMessage(message==null?getString(R.string.not_available):message).setPositiveButton(android.R.string.ok,null).show();}
    private void confirm(String message,Runnable action){new AlertDialog.Builder(this).setMessage(message).setPositiveButton(R.string.confirm,(d,w)->{try{action.run();}catch(Exception e){error(e.getMessage());}}).setNegativeButton(R.string.cancel,null).show();}
    private void startAvailability(){JSONObject c=new ConfigStore(this).load();if(c.optString("token").isEmpty()){tab=0;render();return;}try{c.put("available",true);new ConfigStore(this).save(c);startForegroundService(new Intent(this,AgentService.class).setAction(AgentService.START));}catch(Exception e){error("Could not start availability: "+e.getMessage());}}
    private void render(){if(content==null)return;content.removeAllViews();messageList=null;number=message=null;lineChoice=routeChoice=null;
        JSONObject config=new ConfigStore(this).load();if(config.optString("token").isEmpty()){setup(config);updateState();return;}
        switch(tab){case 1:callPage();break;case 2:messagePage();break;case 3:readerPage();break;case 4:settingsPage(config);break;default:homePage(config);}updateState();}
    private void setup(JSONObject config){label(getString(R.string.login_hint));server=input(R.string.server,false);server.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI);server.setText(config.optString("server"));pin=input(R.string.fingerprint,false);pin.setText(config.optString("pin"));username=input(R.string.username,false);username.setText("admin");password=input(R.string.password,true);
        Button connect=button(R.string.connect,()->login());connect.setId(R.id.connect_gateway);
        button(R.string.scan,()->new IntentIntegrator(this).setDesiredBarcodeFormats(IntentIntegrator.QR_CODE).setBeepEnabled(false).setPrompt("MDD setup").initiateScan());
        button(R.string.import_setup,()->{EditText v=new EditText(this);v.setHint("{\"type\":\"mdd-agent-setup\",…}");new AlertDialog.Builder(this).setTitle(R.string.import_setup).setView(v).setPositiveButton(R.string.confirm,(d,w)->importSetup(v.getText().toString())).setNegativeButton(R.string.cancel,null).show();});
        button(R.string.help,()->error(getString(R.string.help_text)));}
    private void login(){final String origin=server.getText().toString(),fingerprint=pin.getText().toString(),user=username.getText().toString(),pass=password.getText().toString();password.setText("");if(pass.isEmpty()){error("Password required");return;}notice.setText("Verifying gateway…");findViewById(R.id.connect_gateway).setEnabled(false);
        io.execute(()->{GatewayApi candidate=null;try{Endpoint e=new Endpoint(origin,fingerprint);candidate=new GatewayApi(e,"","");candidate.login(user,pass);JSONObject cfg=new ConfigStore(this).load();if(!cfg.optString("server").equals(e.origin)){cfg.remove("agent_token");cfg.remove("agent_id");cfg.remove("share");}cfg.put("server",e.origin).put("pin",e.fingerprint).put("token",candidate.token).put("csrf",candidate.csrf).put("available",true);new ConfigStore(this).save(cfg);runOnUiThread(()->{if(isFinishing())return;requestNotification();startAvailability();render();});}
            catch(Exception e){runOnUiThread(()->{if(!isFinishing()){View b=findViewById(R.id.connect_gateway);if(b!=null)b.setEnabled(true);error("Sign in failed: "+RemoteCall.safe(e));}});}finally{if(candidate!=null)candidate.close();}});}
    private void importSetup(String data){try{Setup s=new Setup(data);confirm("Connect to "+s.endpoint.origin+"?\n\nVerify this origin and certificate fingerprint with your gateway administrator.\n"+s.endpoint.fingerprint,()->{JSONObject c=new JSONObject();try{c.put("server",s.endpoint.origin).put("pin",s.endpoint.fingerprint).put("agent_id",s.agentID).put("agent_token",s.agentToken);new ConfigStore(this).save(c);render();}catch(Exception e){error(e.getMessage());}});}catch(Exception e){error(e.getMessage());}}
    @Override protected void onActivityResult(int code,int result,Intent data){IntentResult scan=IntentIntegrator.parseActivityResult(code,result,data);if(scan!=null){if(scan.getContents()!=null)importSetup(scan.getContents());}else super.onActivityResult(code,result,data);}
    private void requestNotification(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},21);}
    private void homePage(JSONObject c){label(c.optString("server"));label("One app · server calls and messages · attached SIM readers");button(service!=null&&service.available()?R.string.pause:R.string.resume,()->{if(service!=null&&service.available())service.pause();else{requestNotification();startAvailability();}});
        if(service!=null){JSONArray lines=Json.array(service.snapshot,"lines");label(lines.length()+" gateway lines");for(int i=0;i<lines.length();i++){JSONObject l=lines.optJSONObject(i);if(l!=null)label(lineLabel(l));}if(service.snapshot.optBoolean("incomplete"))label("Some lines are temporarily unavailable or the 128-line mobile limit was reached.");}
        label("Reader online ≠ VoWiFi registered. Open Calls to choose the exact line and route.");button(R.string.help,()->error(getString(R.string.help_text)));}
    private String lineLabel(JSONObject l){String id=l.optString("card_id");return l.optString("name",l.optString("id"))+" · …"+id.substring(Math.max(0,id.length()-4))+" · "+(l.optBoolean("enabled")?l.optString("ims","unknown"):"disabled");}
    private JSONArray lines(){return service==null?new JSONArray():Json.array(service.snapshot,"lines");}
    private void selectors(){JSONArray list=lines();selectionSnapshot=list;ArrayList<String> labels=new ArrayList<>();int selected=0;for(int i=0;i<list.length();i++){JSONObject l=list.optJSONObject(i);labels.add(l==null?"Unavailable":lineLabel(l));if(l!=null&&l.optString("id").equals(selectedLine))selected=i;}
        if(labels.isEmpty())labels.add("No lines. Connect or refresh.");lineChoice=new Spinner(this);lineChoice.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,labels));lineChoice.setSelection(selected);content.addView(lineChoice);
        routeChoice=new Spinner(this);routeChoice.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"VoWiFi · server / eSIM reader","Cellular · server modem"}));content.addView(routeChoice);}
    private JSONObject selected(){int index=lineChoice==null?-1:lineChoice.getSelectedItemPosition();JSONObject l=selectionSnapshot.optJSONObject(index);if(l==null)throw new IllegalArgumentException("No gateway line selected");selectedLine=l.optString("id");return l;}
    private String route(){return routeChoice!=null&&routeChoice.getSelectedItemPosition()==1?"cellular":"vowifi";}
    private void callPage(){selectors();number=input(R.string.number,false);number.setInputType(InputType.TYPE_CLASS_PHONE);button(R.string.dial,()->{JSONObject l=selected();String mode=route(),target=number.getText().toString();confirm(getString(R.string.call_confirm)+"\n\n"+lineLabel(l)+" · "+mode+"\n"+target,()->startCall(l,mode,target,null));});
        button(R.string.device_dial,()->{String value=number.getText().toString();try{String target=CallPlan.dialTarget(value);startActivity(new Intent(Intent.ACTION_DIAL,Uri.fromParts("tel",target,null)));}catch(Exception e){error("System dialer unavailable or invalid number");}});button(R.string.refresh,this::render);label("Phone SIM calling is handed to Android. USB readers use server VoWiFi, not the phone radio. Gateway emergency calling/location is not provided.");}
    private void startCall(JSONObject l,String mode,String number,JSONObject incoming){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},22);error("Grant microphone access, then tap Call/Answer again.");return;}try{if(service==null)throw new IllegalStateException("Connect first");service.begin(new CallPlan(l,mode,number,incoming));}catch(Exception e){error(e.getMessage());}}
    private void messagePage(){selectors();number=input(R.string.number,false);number.setInputType(InputType.TYPE_CLASS_PHONE);message=input(R.string.sms_body,false);message.setSingleLine(false);message.setMinLines(3);button(R.string.send,()->{JSONObject l=selected();String mode=route(),target=number.getText().toString(),body=message.getText().toString();confirm(getString(R.string.sms_confirm)+"\n\n"+lineLabel(l)+" · "+mode+"\n"+target,()->{try{if(service==null)throw new IllegalStateException("Connect first");service.sendSMS(l,mode,target,body);message.setText("");}catch(Exception e){error(e.getMessage());}});});
        JSONObject marker=new ConfigStore(this).load().optJSONObject("last_sms");if(marker!=null)label("Last submission: "+marker.optString("state")+" · "+marker.optString("operation_id"));button(R.string.refresh,this::render);
        label("Recent gateway messages (latest 50)");messageList=new LinearLayout(this);messageList.setOrientation(LinearLayout.VERTICAL);content.addView(messageList);updateMessages();}
    private void updateMessages(){if(messageList==null||service==null)return;messageList.removeAllViews();JSONArray messages=Json.array(service.snapshot,"messages");for(int i=0;i<messages.length();i++){JSONObject m=messages.optJSONObject(i);if(m!=null)messageList.addView(text(m.optString("transport")+" · "+m.optString("kind")+" · "+m.optString("sender",m.optString("recipient"))+"\n"+m.optString("body"),15));}}
    private void updateSelection(){if(lineChoice==null)return;JSONObject old=selectionSnapshot.optJSONObject(lineChoice.getSelectedItemPosition());String id=old==null?selectedLine:old.optString("id");JSONArray list=lines();ArrayList<String> labels=new ArrayList<>();int selected=0;for(int i=0;i<list.length();i++){JSONObject l=list.optJSONObject(i);labels.add(lineLabel(l));if(l.optString("id").equals(id))selected=i;}if(labels.isEmpty())labels.add("No lines. Connect or refresh.");selectionSnapshot=list;lineChoice.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,labels));lineChoice.setSelection(selected);}
    private void readerPage(){if(service!=null){label(service.readerStatus);button(service.sharing()?R.string.pause:R.string.share,()->{if(service.sharing())service.shareReaders(false);else confirm(getString(R.string.consent_share),()->service.shareReaders(true));});JSONArray rs=Json.array(service.readers(),"readers");for(int i=0;i<rs.length();i++){JSONObject r=rs.optJSONObject(i);String card=r.optString("card_id");label(r.optString("reader_name")+" · …"+card.substring(Math.max(0,card.length()-4))+"\n"+Json.object(r,"sim").optString("identity_state"));}}
        UsbManager usb=getSystemService(UsbManager.class);for(UsbDevice device:usb.getDeviceList().values()){boolean ccid=false;for(int i=0;i<device.getInterfaceCount();i++)ccid|=device.getInterface(i).getInterfaceClass()==11;if(!ccid)continue;button(content,getString(R.string.usb_permission)+" · "+device.getVendorId()+":"+device.getProductId(),()->{Intent intent=new Intent(getPackageName()+".USB_PERMISSION").setPackage(getPackageName());int flags=PendingIntent.FLAG_UPDATE_CURRENT|(Build.VERSION.SDK_INT>=31?PendingIntent.FLAG_MUTABLE:0);usb.requestPermission(device,PendingIntent.getBroadcast(this,device.getDeviceId(),intent,flags));});}
        button(R.string.refresh,()->{if(service!=null)service.refreshReaders();render();});button(R.string.help,()->error(getString(R.string.help_text)));}
    private void settingsPage(JSONObject c){label(c.optString("server"));label("TLS: "+(c.optString("pin").isEmpty()?"System certificate trust":"Pinned certificate"));label("Sessions are Keystore-encrypted. Passwords are never saved. A revoked/expired session requires sign-in again.");
        button(R.string.battery,()->{try{startActivity(new Intent(Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS));}catch(Exception e){startActivity(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())));}});
        button(R.string.gateway,()->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(c.optString("server")))));button(content,"Share safe diagnostics",()->{Intent share=new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,"MDD Agent preview 0.1\nAndroid API "+Build.VERSION.SDK_INT+"\nAvailability: "+(service!=null&&service.available())+"\nGateway online: "+(service!=null&&service.online())+"\nUSB host: "+getPackageManager().hasSystemFeature(PackageManager.FEATURE_USB_HOST)+"\nNo tokens, SIM identities or message contents included.");startActivity(Intent.createChooser(share,"Diagnostics"));});
        button(content,"Sign in again",()->{if(service!=null&&service.accountBusy()){error("Resolve the current call or wait for the current operation first");return;}if(service!=null)service.pause();JSONObject cfg=new ConfigStore(this).load();cfg.remove("token");cfg.remove("csrf");new ConfigStore(this).save(cfg);tab=0;render();});button(R.string.logout,()->confirm("Stop reader sharing and incoming notifications on this device?",()->{if(service!=null)service.logout();render();}));button(R.string.help,()->error(getString(R.string.help_text)));label("Preview 0.1 · API 28+ · no cloud relay/FCM dependency\nAfter force-stop/reboot, open the app and choose Stay available. Screen-off behavior must be qualified on your phone.");}
    private void updateState(){if(status==null)return;status.setText(service==null?"Connecting to local service":service.connection);notice.setText(service==null?"":service.notice);callBox.removeAllViews();if(service==null)return;
        if(lastData!=service.snapshot){lastData=service.snapshot;if(tab==0&&!new ConfigStore(this).load().optString("token").isEmpty()){content.removeAllViews();homePage(new ConfigStore(this).load());}else{updateSelection();updateMessages();}}
        RemoteCall current=service.call;if(current!=null){callBox.addView(text(current.plan.number+" · "+current.plan.mode+"\n"+current.state,16));LinearLayout row=new LinearLayout(this);callBox.addView(row);button(row,getString(R.string.hangup),service::hangup);if(current.audio!=null&&!current.audio.closed){button(row,getString(R.string.mute),()->current.audio.mute());button(row,getString(R.string.speaker),()->current.audio.speaker());button(callBox,"DTMF",()->{EditText digit=new EditText(this);digit.setInputType(InputType.TYPE_CLASS_PHONE);new AlertDialog.Builder(this).setTitle("DTMF · one digit").setView(digit).setPositiveButton(R.string.send,(d,w)->current.dtmf(digit.getText().toString())).setNegativeButton(R.string.cancel,null).show();});}return;}
        JSONArray lines=lines();for(int i=0;i<lines.length();i++){JSONObject l=lines.optJSONObject(i);JSONObject incoming=l==null?null:l.optJSONObject("incoming");if(incoming!=null){incoming(l,"vowifi",incoming);return;}}
        JSONArray cells=Json.array(service.snapshot,"cellular_calls");for(int i=0;i<cells.length();i++){JSONObject in=cells.optJSONObject(i);if(in==null||!in.optBoolean("actionable"))continue;for(int j=0;j<lines.length();j++){JSONObject l=lines.optJSONObject(j);if(l!=null&&l.optString("id").equals(in.optString("line_id"))){incoming(l,"cellular",in);return;}}}
    }
    private void incoming(JSONObject line,String mode,JSONObject call){callBox.addView(text(getString(R.string.incoming_call)+" · "+mode+"\n"+call.optString("caller",call.optString("number")),18));LinearLayout row=new LinearLayout(this);callBox.addView(row);button(row,getString(R.string.answer),()->startCall(line,mode,"",call));button(row,getString(R.string.reject),()->service.reject(line,mode,call));}
}
