import { resolvedStates } from './acceptance-policy.mjs'
const escape = value => value.replaceAll('|', '\\|').replaceAll('\n', ' ')
const generated = source => `<!-- Generated by tools/repository-check.mjs; edit ${source}. -->\n\n`
const scopeTable = ledger => '| Scope | Disposition | Current decision |\n|---|---|---|\n' +
  ledger.releaseScope.map(x => `| ${x.id} | ${x.disposition} | ${escape(x.summary)} |`).join('\n') + '\n'
const workSection = items => items.map(x => `### ${x.id}\n\n**State: ${x.state}; release relevance: ${x.releaseRelevance}.** ${x.summary}\n\n` +
  `Acceptance scope / remaining action: ${x.acceptance}\n\n` + (x.resolution ? `Resolution (${x.resolution.basis}): ${x.resolution.reason}\n\n` : '')).join('')
const workGroups = ledger => {
  const active = ledger.workstreams.filter(x => !resolvedStates.has(x.state) && x.releaseRelevance === 'current')
  const other = ledger.workstreams.filter(x => !active.includes(x))
  return '## Current open work\n\n' + workSection(active) + '## Accepted, deferred, excluded and separately prioritized work\n\n' + workSection(other)
}
export function summaries(ledger) {
  const counts = key => [...new Set(ledger.criteria.map(row => row[key]))].sort()
    .map(state => `- ${state}: ${ledger.criteria.filter(row => row[key] === state).length}`).join('\n')
  const table = rows => '| Criterion | Implementation | Acceptance / evidence | Current requirement (original preserved in detail) |\n|---|---|---|---|\n' +
    rows.map(row => `| [${row.id}](docs/status/README.md#${row.id.toLowerCase()}) | ${row.implementation} | ${row.acceptance} | ${escape(row.currentRequirement || row.requirement)} |`).join('\n') + '\n'
  const intro = 'All 59 original general criteria and four macOS criteria remain preserved. Current owner decisions take precedence over superseded wording. ' +
    'Implementation, scoped historical evidence, this review and production deployment are separate facts. A green build is not field acceptance; not revalidated is not never accepted.\n\n'
  const root = '# Current rewrite scope and acceptance\n\n' + generated('docs/status/acceptance.json') + intro +
    '[Current decisions](docs/decisions/2026-09-20-current-scope.md) · [Detailed ledger](docs/status/README.md) · [Issue #3](https://github.com/lovitus/mdd-sim-gateway/issues/3).\n\n' +
    scopeTable(ledger) + '\n' + table(ledger.criteria.filter(row => row.origin.document === 'TODO.md'))
  const mac = '# macOS scope and evidence\n\n' + generated('docs/status/acceptance.json') +
    'Signing, notarization and architecture packaging are separate claims. Current scope decisions below take precedence over the preserved original combined checkbox.\n\n' + intro + scopeTable(ledger) + '\n' +
    table(ledger.criteria.filter(row => row.origin.document === 'TODO_MACOS_AGENT.md'))
  let status = '# Versioned scope, implementation and acceptance ledger\n\n' + generated('acceptance.json') +
    `Original audit baseline: \`${ledger.baseline}\`; tree \`${ledger.baselineTree}\`; review ${ledger.reviewDate}.\nScope-correction baseline: \`${ledger.correctionBaseline}\`; tree \`${ledger.correctionBaselineTree}\`.\n\n${ledger.scope}\n\n` +
    '## Reading and updating the ledger\n\n' + intro +
    '`implemented` means identified source exists, not universal qualification. `covered_by_tests` is automated-contract coverage. ' +
    '`evidence_review_pending` preserves existing scoped field reports for reconciliation, not fresh acceptance and not a request to repeat all tests. ' +
    '`pending_hardware` means specific field scenarios remain unresolved; it does not prove no prior test ever happened. ' +
    '`pending_product` is an actual implementation/scope question. Original text is historical where a current requirement is supplied.\n\n' +
    'Workstream `accepted` with a `user_decision` basis records accepted product direction, not fresh hardware tests. ' +
    '`completed`, `accepted`, `superseded`, `deferred` and `cancelled` are valid evidence-bearing transitions; required IDs preserve history, not perpetual open tasks. ' +
    'Future decisions can change scope through a new decision reference and rationale; do not delete requirements to close them.\n\n' +
    'Historical report hashes identify the exact **report excerpt**, not an unavailable device binary or raw capture. ' +
    'Verified existing acceptance and new hardware acceptance require their own dated/environment/artifact/report metadata. ' +
    'CI validates structure and provenance consistency, not physical truth. Do not publish credentials or raw device identifiers.\n\n' +
    'Use traceable local records to update this ledger; latest explicit owner decisions override stale scope. ' +
    'Reconcile earlier reports and test only uncovered/contradicted cases with authorization. ' +
    'Run `node tools/repository-check.mjs --write` and review the generated diff.\n\n' +
    '## Current release scope\n\n' + scopeTable(ledger) + '\n## Decision provenance\n\n' +
    ledger.decisions.map(d => `- **${d.id}** (${d.date}, ${d.authority}): ${d.summary} [Source](../../${d.sourcePath}).`).join('\n') + '\n\n' +
    '## Disposition counts\n\n### Implementation\n\n' + counts('implementation') + '\n\n### Acceptance / evidence\n\n' + counts('acceptance') + '\n\n' + workGroups(ledger) +
    '## Preserved historical evidence\n\n'
  for (const item of ledger.evidenceRecords) status += `### ${item.id}\n\n**${item.reviewState}.** ${item.summary}\n\n` +
    `[Report lines ${item.startLine}–${item.endLine}](../../${item.reportPath}#L${item.startLine}) · excerpt SHA-256 \`${item.excerptSHA256}\`.\n\n` +
    `Limits: ${item.limitations}\n\nLinked criteria: ${item.criteria.map(id => `[${id}](#${id.toLowerCase()})`).join(', ')}.\n\n`
  status += '## All original criteria and current dispositions\n\n'
  for (const row of ledger.criteria) {
    const archive = ledger.archives.find(item => item.original === row.origin.document)
    status += `### ${row.id}\n\n**Implementation: ${row.implementation}; acceptance/evidence: ${row.acceptance}.**\n\n` +
      (row.currentRequirement ? `**Current requirement:** ${row.currentRequirement}\n\n` : '') +
      `Preserved original ([${row.origin.document}:${row.origin.line}](../../${archive.path}#L${row.origin.line})): ${row.requirement.replaceAll('\n', ' ')}\n\n` +
      `${row.rationale}\n\n` + (row.historicalEvidence.length ? `Existing reports: ${row.historicalEvidence.map(id => `[${id}](#${id.toLowerCase()})`).join(', ')}.\n\n` : '') +
      (row.remainingAcceptance ? `Remaining scope: ${row.remainingAcceptance}\n\n` : '') +
      `Source/test boundaries: ${row.evidence.map(p => `[\`${p}\`](../../${p})`).join(', ')}.\n\n`
  }
  const postponed = '# Current open work and accepted/deferred decisions\n\n' + generated('docs/status/acceptance.json') + intro +
    'See [current decisions](docs/decisions/2026-09-20-current-scope.md) and [scoped existing reports](docs/status/README.md#preserved-historical-evidence). ' +
    'The [archived notes](docs/archive/2026-09-20/postponed-tasks.md) preserve original reports and hypotheses; a new review does not revoke them. ' +
    'Deferred and excluded scope is not a current blocker; accepted direction is not new physical acceptance.\n\n' + scopeTable(ledger) + '\n' + workGroups(ledger)
  return Object.fromEntries(Object.entries({ 'TODO.md': root, 'TODO_MACOS_AGENT.md': mac, 'postponed-tasks.md': postponed, 'docs/status/README.md': status }).map(([p, s]) => [p, s.trimEnd() + '\n']))
}
