import assert from 'node:assert/strict'
import fs from 'node:fs'

const read = name => fs.readFileSync(new URL(`../src/${name}`, import.meta.url), 'utf8')
const app = read('App.jsx')
const api = read('api.js')
const calls = read('views/CallsV1.jsx')
const routeSelection = read('routeSelection.js')
const coordinator = read('goCallCoordinator.jsx')
const media = read('goCallMedia.js')
const sim = read('views/SimConfigV1.jsx')

for (const source of [app, api, calls, coordinator, media]) {
  assert.ok(!source.includes('mediaIngress'), 'same-origin media must never ask users to confirm an interface or IP')
  assert.ok(!source.includes('createMediaPhone'))
  assert.ok(!source.includes('BrowserPhone'))
}
assert.ok(!fs.readFileSync(new URL('../package-lock.json', import.meta.url), 'utf8').includes('jssip'))
assert.ok(app.includes('useGoCallCoordinator({'))
assert.ok(app.includes('<GlobalGoCallOverlay coordinator={callCoordinator}'))
assert.ok(coordinator.includes('if (currentRef.current) throw new Error'))
assert.ok(coordinator.includes('media.openAudioFromGesture()'))
assert.ok(coordinator.indexOf('media.openAudioFromGesture()') < coordinator.indexOf('await api.createCallMediaLease'))
assert.ok(coordinator.includes("call.mode === 'cellular'"))
assert.ok(coordinator.includes('incoming_event_id: incoming.incoming_event_id'))
assert.ok(coordinator.includes('sim_session_generation: incoming.sim_session_generation'))
assert.ok(coordinator.includes('native_call_index: incoming.native_call_index'))
assert.ok(coordinator.includes('call_occurrence: incoming.occurrence'))
assert.ok(coordinator.includes('call.media?.close()'))
assert.ok(coordinator.indexOf('call.media?.close()') < coordinator.indexOf('await api.hangupCallV1(call)'))
assert.ok(coordinator.includes('The 10-second exact call guard'))
assert.ok(
  coordinator.includes("call.mode === 'cellular') return Promise.resolve()"),
  'an uncertain cellular start cannot be submitted twice')
assert.ok(media.includes("`${scheme}://${location.host}${this.lease.ws_path}`"))
assert.ok(media.includes("type: 'browser.media.evidence'"))
assert.ok(media.includes('this.reconnectDeadline = Date.now() + 9000'))
assert.ok(media.includes('this.socket.bufferedAmount + FRAME_BYTES <= limitBytes'))
assert.ok(media.includes("new URL('./browserMediaWorklet.js', import.meta.url)"))
assert.ok(routeSelection.includes("['vowifi', 'vowifi_call']"))
assert.ok(routeSelection.includes("['cellular', 'cellular_call']"))
assert.ok(routeSelection.includes('line.operations?.[key]'))
assert.ok(calls.includes('Temporary jitter does not end a call.'))
assert.ok(sim.includes('value={draft.id} readOnly'))
assert.ok(sim.includes('Apply is a separate explicit action.'))
assert.ok(api.includes("'/v1/media/leases'"))
assert.ok(api.includes("'/v1/cellular/media/leases'"))
assert.ok(api.includes('/cellular/calls/hangup'))
assert.ok(api.includes('/vowifi/calls/end'))

console.log('Go same-origin browser voice admission, exact hangup, and no-IP-confirmation contracts passed')
