import assert from 'node:assert/strict'
import fs from 'node:fs'

const read = name => fs.readFileSync(new URL(`../src/${name}`, import.meta.url), 'utf8')
const app = read('App.jsx')
const api = read('api.js')
const view = read('views/Softphone.jsx')
const coordinator = read('callCoordinator.jsx')
const native = read('browserMedia.js')
const cellular = read('cellularBrowserCall.js')
const incoming = read('cellularIncomingCoordinator.js')
const simConfig = read('views/SimConfig.jsx')

assert.ok(!simConfig.includes('Enable browser softphone (WebRTC)'),
  'native-only calling must not show an ineffective legacy SIP/WebRTC switch')
assert.ok(!simConfig.includes('checked={!!form.sip.webrtc?.enable}'))

for (const source of [app, view, coordinator, api]) {
  assert.ok(!source.includes('mediaIngress'), 'the same-origin media path must not request an interface/IP confirmation')
  assert.ok(!source.includes('createMediaPhone'))
  assert.ok(!source.includes('BrowserPhone'))
}
assert.ok(!fs.existsSync(new URL('../src/softphone.js', import.meta.url)))
assert.ok(!fs.readFileSync(new URL('../package-lock.json', import.meta.url), 'utf8').includes('jssip'))
assert.ok(app.includes('useCallCoordinator({'))
assert.ok(app.includes('<GlobalCallOverlay coordinator={callCoordinator}'))
assert.ok(coordinator.includes('api.softphone(key)'))
assert.ok(coordinator.includes('new NativeBrowserCall(key, number'))
assert.ok(coordinator.includes('provision?.browser_media?.outbound === true'))
assert.ok(coordinator.includes('const existing = linesRef.current[key]?.call'))
assert.ok(coordinator.includes('This line is already in use'))
assert.ok(coordinator.includes('verifyBrowserMedia(key)'))
assert.ok(native.includes('api.prepareBrowserOutbound(this.instanceId, this.destination)'))
assert.ok(native.includes("type: 'browser.call.hangup'"))
assert.ok(native.includes("type: 'browser.call.dtmf'"))
assert.ok(native.includes('revision <= this.lastCallRevision'))
assert.ok(native.includes('if (await this._stopIfEnding()) return'))
assert.ok(native.includes('muted() ? silence.slice(0) : frame'))
assert.ok(native.includes('connectPcmAudio(this.context, this.stream'))
assert.ok(cellular.includes('connectPcmAudio(this.context, this.stream'))
assert.ok(cellular.includes("owner_token: this.ownerToken"))
assert.ok(cellular.includes('crypto.getRandomValues(new Uint8Array(32))'))
assert.ok(cellular.includes('this.commitRequested || this.ending || this.finished'))
assert.ok(cellular.indexOf('await navigator.mediaDevices.getUserMedia') < cellular.indexOf('await this.api.prepareIncomingCellularCall'))
assert.ok(!cellular.includes('cellularCallHangup'))
assert.ok(!cellular.includes('submitCellularMediaEvidence'))
assert.ok(!incoming.includes('prepareIncomingCellularCall'), 'ringing controller must not prepare before user action')
assert.ok(incoming.includes('item.cellular_owner_call_id === this.mediaPhone.callId'))
assert.ok(incoming.includes("this._endSoon('Answered elsewhere')"))
assert.ok(view.includes('Normal call charges may apply.'))
assert.ok(view.includes('new CellularBrowserCall'))
assert.ok(view.includes("callTransport === 'vowifi' ? !vowifiReady : !cellularReady"))
const placeCall = view.slice(view.indexOf('const placeCall = async'), view.indexOf('const answer = async'))
assert.ok(placeCall.indexOf('if (!vowifiReady)') < placeCall.indexOf('callCoordinator.call(id, target)'))
const verify = view.slice(view.indexOf('const verifyMedia ='), view.indexOf('// in-call duration timer'))
assert.ok(verify.indexOf('if (!browserMediaAvailable || call)') < verify.indexOf('callCoordinator.verifyMedia(id)'))
assert.ok(coordinator.includes("const answerable = call.source === 'native-wss-incoming'"))
assert.ok(coordinator.includes('call.answerable !== false && call.exactIdentity'))
console.log('Same-origin browser voice admission and no-IP-confirmation tests passed')
